### PR TITLE
Added date plugin

### PR DESCRIPTION
**Pull request by CiaranFahy**
# brief description of changes
issue  #73

### CODE REVIEW

**Comment by CiaranFahy** [comment]
Could you clarify for me?

I thought you wanted a seperate plugin? Not the date printed in .greet

**Comment by CiaranFahy** [comment]
> good but modify the greet plugin for example == '.date'
> 
> now if we use it, it won't do anything

**Comment by Abdur-rahmaanJ** [comment]
@CiaranFahy like try it in irc. ever used IRC?

**Comment by Abdur-rahmaanJ** [comment]
@CiaranFahy like try it in irc. ever used IRC?

**Comment by Abdur-rahmaanJ** [comment]
someone else took it over, please brwose other issues of feel free to propose 1

**Pull request closed without merging**
