### PR TITLE
Monopoly plugin

### PR DESCRIPTION
**Pull request by justinwalker4179**
Adds in all asset info from the game for whomever wants to make a game out of them.
Info comes from a very old copy, so it may have changed in newer versions.

Contributes to https://github.com/Abdur-rahmaanJ/honeybot/issues/26

### CODE REVIEW

**Comment by Macr0Nerd** [comment]
@justinwalker4179 Please refer to the plugin instructions in the readme. On `hangman.py` you defined the command as `.selfTrivia` when that is taken, and you have also not made a game.

In `monopoly.py` you provide all the assets, and seem to leave it up to the players to figure play the board. It seems fine to me, but we should get @Abdur-rahmaanJ to confirm this is alright. But there also isn't any `Plugin` class for the game to be run at all.

With these operations in mind please append the comments and submit a new pull request. To keep the upstream as valid plugins I am going to close this one but will leave it unlocked for any further questions and such.

**Comment by justinwalker4179** [comment]
Please read my PR message which states that it was meant to provide assets for anyone who wishes to make the game in the future. Not everyone may have the game, and won't need to buy it. This way when someone feels like taking it on, the boring grunt work stuff is over. Wasn't sure if there was a better way to provide these then a PR, closed or not. Also hangman.py was an accidental file for something else I'm working on which was removed in the next commit, I can go back in and delete that commit entirely if it's a problem.

**Comment by Macr0Nerd** [comment]
I will see what I can do about the hangman file. And I apologize I must've missed that these were asset files specifically.

**Comment by justinwalker4179** [comment]
No worries, I'm still very new to PR's. Wasn't sure I could tackle the whole game, but I still wanted to help 😃 If there's a more appropriate place or format for this I'd be glad to change it.

**Comment by Macr0Nerd** [comment]
I removed the hangman file and the game logic section from the file, along with renaming it to `monopolyassets.py`. This way no one gets confused about the purpose of this file, and we can keep all the logic of the game in the plugin file itself.

This is great work and I hope we see more help from you in the future!

**Comment by Abdur-rahmaanJ** [comment]
@justinwalker4179 actually very useful!

**Pull request merged**
