### PR TITLE
added abbreviation plugin

### PR DESCRIPTION
**Pull request by chibitofu**
Created abbreviation.py with code for basic plugin functionality.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
see the command well. it should be .def lol

**Comment by chibitofu** [comment]
Is this how the code should read?

if info['command'] == 'PRIVMSG' and info['args'][1] == '.def lol':

**Comment by Abdur-rahmaanJ** [comment]
@chibitofu 

... and info['args'][2] == lol

**Comment by chibitofu** [comment]
Like this?
if info['command'] == 'PRIVMSG' and info['args'][1] == '.def' and info['args'][2] == 'lol':

**Comment by Abdur-rahmaanJ** [comment]
or you can add the 2 in a second if condition

...  == '.def':
     if info....2.. == 'lol':

**Comment by chibitofu** [comment]
Updated abbreviation.py with corrections.

**Pull request merged**
