### PR TITLE
add comic plugin

### PR DESCRIPTION
**Pull request by mboekhold**
# brief description of changes
This commit adds a new plugin to get random comics on request

### CODE REVIEW

**Comment by nickw409** [comment]
The file for the plugin isn't in the right place, make sure all plugins are in the plugin folder.

**Comment by mboekhold** [comment]
Oops :sweat_smile:

**Comment by mboekhold** [comment]
@AngeloGiacco Do i remove the flag?

**Comment by mboekhold** [comment]
running `pluginInfo.py` restructures the whole file for some reason

**Pull request merged**
